Create empty activity
camelot1402/AndroidDev2021 pull request #1
Opened 2021-03-01 07:15 UTC by camelot1402

Add project

2021-03-01 07:29 UTC, murrcha requested changes
Папку .idea необходимо добавить в корневой .gitignore, чтобы исключить ее из репозитория

Для внесения изменений допустимо делать новый коммит, но тогда будет несколько коммитов по одному PR (это часто засоряет историю, как правило, 1 задача - 1 коммит).
На практике обычно изменения по ходу ревью добавляют уже в текущий коммит локально и пушат их с флагом -f для перезаписи коммита в удаленной ветке.

2021-03-02 06:44 UTC, murrcha requested changes
Папка .idea все еще в репозитории
PR должен быть атомарным - 1 задача - 1 коммит
Сейчас PR содержит 3 коммита
Необходимо их схлопнуть (squash) в один коммит, используя интерактивный rebase

2021-03-03 15:27 UTC, thealbre commented
В целом хорошо, осталось только 
- добавить readme.md
- расширить gitignore и добавить туда к примеру `/*/out`, `*.apk` и др.
- после этого сделать squash коммитов в 1 коммит 

и можно мержить

2021-03-03 17:43 UTC, camelot1402 commented
> 
> 
> Папку .idea необходимо добавить в корневой .gitignore, чтобы исключить ее из репозитория
> 
> Для внесения изменений допустимо делать новый коммит, но тогда будет несколько коммитов по одному PR (это часто засоряет историю, как правило, 1 задача - 1 коммит).
> На практике обычно изменения по ходу ревью добавляют уже в текущий коммит локально и пушат их с флагом -f для перезаписи коммита в удаленной ветке.

Исправлено

2021-03-03 17:51 UTC, thealbre approved these changes

2021-03-04 05:49 UTC, murrcha approved these changes

2021-03-04 08:04 UTC, merged